// frameworks/solid/test.tsx
import { createComponent, createSignal } from "solid-js";
import { render, renderToString, hydrate, generateHydrationScript } from "solid-js/web";

import Neodt, { type NeodtProps } from "./generic";
export function renderServer<T, TZone>(props: NeodtProps<T, TZone>) {
  return renderToString(() => createComponent(Neodt<T, TZone>, props));
}
export function mount<T, TZone>(
  element: HTMLElement,
  initial: NeodtProps<T, TZone>,
  hydrating = false,
) {
  const [props, setProps] = createSignal(initial);
  const dispose = (hydrating ? hydrate : render)(() => <Neodt {...props()} />, element);
  return { update: (next: NeodtProps<T, TZone>) => setProps(next), dispose };
}

export const hydrationScript = generateHydrationScript;

// frameworks/react/test.tsx
import { createElement, act, StrictMode } from "react";
import { createRoot, hydrateRoot } from "react-dom/client";
import { renderToString } from "react-dom/server";

import Neodt, { type NeodtProps } from "./generic";
export function renderServer<T, TZone>(props: NeodtProps<T, TZone>) {
  return renderToString(createElement(Neodt<T, TZone>, props));
}
export async function mount<T, TZone>(
  element: HTMLElement,
  initial: NeodtProps<T, TZone>,
  hydrating = false,
) {
  const view = (props: NeodtProps<T, TZone>) =>
    createElement(StrictMode, null, createElement(Neodt<T, TZone>, props));
  let root!: ReturnType<typeof createRoot>;
  await act(async () => {
    root = hydrating ? hydrateRoot(element, view(initial)) : createRoot(element);
    if (!hydrating) root.render(view(initial));
  });
  return {
    update: async (next: NeodtProps<T, TZone>) => {
      await act(async () => root.render(view(next)));
    },
    dispose: async () => {
      await act(async () => root.unmount());
    },
  };
}
